### ISSUE TITLE
Mythic installation error

### ISSUE THREAD

**Issue by SankarSrinivasan1** [justintadlock/mythic#83]
Justin, Following is the error which is caused during activation of mythic theme. Theme installation failed

Fatal error: Uncaught Error: Class 'Hybrid\Core\Application' not found in /home/sankarsr/public_html/testing/wp-content/themes/mythic-master/app/bootstrap-app.php:23 Stack trace: #0 /home/sankarsr/public_html/testing/wp-content/themes/mythic-master/functions.php(36): require_once() #1 /home/sankarsr/public_html/testing/wp-settings.php(499): include('/home/sankarsr/...') #2 /home/sankarsr/public_html/testing/wp-config.php(90): require_once('/home/sankarsr/...') #3 /home/sankarsr/public_html/testing/wp-load.php(37): require_once('/home/sankarsr/...') #4 /home/sankarsr/public_html/testing/wp-admin/admin.php(34): require_once('/home/sankarsr/...') #5 /home/sankarsr/public_html/testing/wp-admin/themes.php(10): require_once('/home/sankarsr/...') #6 {main} thrown in /home/sankarsr/public_html/testing/wp-content/themes/mythic-master/app/bootstrap-app.php on line 23

The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

**Comment by saas786** [comment]
Please follow the instructions
https://github.com/justintadlock/mythic/wiki/Installation

**Comment by SankarSrinivasan1** [comment]
🙏 thanks
